# in:
#   type: random
#   rows: 100
#   schema:
#     id: primary_key
#     name: string
#     score: integer
in:
  type: file
  path_prefix: example/data.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: time,  type: timestamp, format: "%Y-%m-%d"}
      - {name: id, type: long}
      - {name: name, type: string}
      - {name: score, type: double}
filters:
  - type: distinct
    columns: [time]
out:
  type: stdout
